services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.120.0
    ports:
      - "4318:4318"
    volumes:
      - ./src/common/lib/logger/otel-config.yaml:/etc/otel/config.yaml
    command: ["--config", "/etc/otel/config.yaml"]
    environment:
      - BETTERSTACK_LOGS_TOKEN=${BETTERSTACK_LOGS_TOKEN}
    networks:
      - ecomm-network

networks:
  ecomm-network:
    driver: bridge